project_name: twtarget
builds:
    - main: twtarget.go
      binary: twtarget
      goos:
        - windows
        - darwin
        - linux
      goarch:
        - amd64
archive:
    format: tar.gz
release:
    draft: false
